#
# DATES
#
default_env             : DEV
default_schema          : ''
default_workspace       : ''
default_apps            : []
default_app_group       : ''



#
# DATES
#
today                   : '%Y-%m-%d'        # YYYY-MM-DD
today_full              : '%Y-%m-%d %H:%M'  # YYYY-MM-DD HH24:MI
today_full_raw          : '%Y%m%d%H%M00'
today_custom            : ''
today_patch             : '%y%m%d'          # YYMMDD
today_deploy            : '%Y-%m-%d %H-%M'  # used in deployment logs



#
# BASIC PATHS
#
path_objects            : 'database/'       # folder with database objects
path_apex               : 'apex/'           # folder with APEX related files

# target folders by object types
object_types:
    DATA                : ['data/',         .sql]
    FUNCTION            : ['functions/',    .sql]
    GRANT               : ['grants/',       .sql]
    INDEX               : ['indexes/',      .sql]
    JOB                 : ['jobs/',         .sql]
    MATERIALIZED VIEW   : ['mviews/',       .sql]
    MVIEW LOG           : ['mview_logs/',   .sql]
    PACKAGE             : ['packages/',     .spec.sql]
    PACKAGE BODY        : ['packages/',     .sql]
    PROCEDURE           : ['procedures/',   .sql]
    SEQUENCE            : ['sequences/',    .sql]
    SYNONYM             : ['synonyms/',     .sql]
    TABLE               : ['tables/',       .sql]
    TRIGGER             : ['triggers/',     .sql]
    TYPE                : ['types/',        .sql]
    TYPE BODY           : ['types/',        .body.sql]
    VIEW                : ['views/',        .sql]



#
# PATCH
#
patch_root              : 'patch/'                          # folder with live patches
patch_archive           : 'patch_archive/'                  # folder with archived patches
patch_template_dir      : 'config/patch_template/'          # source folder for all patches
patch_template_snap     : 'patch_template/'                 # folder name inside of your patch folder
patch_scripts_dir       : 'patch_scripts/{$PATCH_CODE}/'    # source folder for specific patch
patch_scripts_snap      : 'patch_scripts/'                  # folder name inside of your patch folder
patch_grants            : 'grants/{$INFO_SCHEMA}.sql'       # location of your grants file
patch_file_link         : '@"./{$FILE}"'                    # file line in patch file
patch_folder            : '{$INFO_SCHEMA}{$TODAY_PATCH}-{$PATCH_SEQ}-{$PATCH_CODE}'
patch_folder_day        : '^([^-]+)'                        # to extract day from patch_folder
patch_folder_cod        : '[-]+(.*)$'                       # to extract patch_code from patch_folder
patch_folder_seq        : '[-]([^-]*)[-]'                   # to extract patch_seq from patch_folder
patch_add_templates     : True                              # process templates
patch_add_scripts       : True                              # process scripts
patch_spooling          : True                              # to SPOOL into file or not
patch_postfix_before    : '_before'                         # for templates and scripts
patch_postfix_after     : '_after'                          # for templates and scripts
patch_deploy_logs       : 'logs_{$TARGET_ENV}'              # prefix for log folder for deployments

# patch map to create patch files in this very order
# and to add files from templates at before/after points
# and to add scripts (manual interventions) at specific points
patch_map:
    sequences:
        - SEQUENCE
    tables:             # group name
        - TABLE         # object type, order is important
    types:
        - TYPE
        - TYPE BODY
    synonyms:
        - SYNONYM
    objects:
        - VIEW
        - PROCEDURE
        - FUNCTION
        - PACKAGE
        - PACKAGE BODY
    triggers:
        - TRIGGER
    mviews:
        - MVIEW LOG
        - MATERIALIZED VIEW
    indexes:
        - INDEX
    data:
        - DATA
    grants:
        - GRANT
    jobs:
        - JOB



#
# EXPORT
#
drop_objects:
    - MATERIALIZED VIEW
    - MVIEW LOG
    - JOB

add_indexes:
    - TABLES
    - MATERIALIZED VIEW



#
# GIT REPOSITORY
#
repo_commits        : 50                        # depth search for the commits history
repo_branch         : dev
repo_commits_file   : './config/commits/#BRANCH#.yaml'



#
# GIT REPOSITORY
#
sqlcl_root          : './.temp.nosync/'         # add to .gitignore, keep flag to avoid cloud sync
sqlcl_temp_file     : 'sqlcl.tmp'



#
# APEX RELATED
#
apex_schema             : '{$INFO_SCHEMA}'
apex_workspace          : '{$INFO_SCHEMA}'
apex_version            : '{$TODAY} {$PATCH_CODE}'
apex_path_app           : '{$APP_ID}_{$APP_ALIAS}'  # classic = 'f{$APP_ID}'
apex_path_files         : 'files/'
apex_path_rest          : 'rest/'
apex_workspace_dir      : 'workspace/'
apex_yaml_file          : 'config/apex.{$APP_WS}.yaml'
apex_snapshots          : 'snapshots/'
#
apex_show_recent        : 1                     # show changes made in past # days
apex_export_full        : False                 # full export
apex_export_split       : True                  # export individual components
apex_format_json        : False                 # export also in JSON format
apex_format_yaml        : True                  # export also in YAML format
apex_export_embedded    : False                 # export Embedded Code report
apex_export_rest        : False                 # export rest services
apex_export_files       : False                 # export application & workspace files
apex_export_files_ws    : False                 # export application & workspace files
#
apex_comments           : True                  # add component names as comments
apex_timestamps         : '20240101000000'      # convert page timestamp to a specific value
apex_authors            : 'DEV'                 # convert page author to a specific value for non developers
apex_authentication     : '[DEFAULT]'           # switch to marked authentication scheme
apex_set_version        : '#TODAY#'             # overwrite application version
apex_workspace_id       : ''                    # override APEX workspace id

# these files will not be in the patch even if they change
apex_files_ignore:
    - /application/set_environment.sql
    - /application/end_environment.sql
    - /application/create_application.sql
    - /application/delete_application.sql
    - /application/pages/delete_*.sql       # wild flag
    - /install.sql
    - /install_component.sql

# these files will always be copied to the snapshot folder
apex_files_copy:
    - /application/set_environment.sql
    - /application/end_environment.sql

