SET SERVEROUTPUT    ON
SET TIMING          ON
SET SQLBLANKLINES   ON
SET DEFINE          OFF
--
--ALTER SESSION DISABLE PARALLEL QUERY;
ALTER SESSION DISABLE PARALLEL DML;
ALTER SESSION DISABLE PARALLEL DDL;
--
ALTER SESSION SET NLS_NUMERIC_CHARACTERS    = '. ';
ALTER SESSION SET NLS_DATE_FORMAT           = 'YYYY-MM-DD HH24:MI';

--
ALTER SESSION SET plscope_settings  = 'IDENTIFIERS:ALL, STATEMENTS:ALL';
ALTER SESSION SET plsql_warnings    = 'DISABLE:INFORMATIONAL,ENABLE:PERFORMANCE,DISABLE:SEVERE';

